### ISSUE TITLE
Autocomplete and hover hints

### ISSUE THREAD

**Issue by awmottaz** [crowdin/vscode-crowdin#67]
**Is your feature request related to a problem? Please describe.**

It would be great if this extension could help me fill in the correct translation keys and provide hover information about a translation key.

**Describe the solution you'd like**

- In my source code, as I start typing a translation key, show me auto-complete suggestions for translation keys in my Crowdin sources files.
- When I hover over a translation key, show information about that translation key, such as the text associated with that key in the source language and possibly its translation status from Crowdin.

I understand that these features require some level of parsing of source files, which the Crowdin app already can do. For my use case, the i18next JSON format, Android XML, and iOS strings are what I need.

**Describe alternatives you've considered**

**Additional context**

I am interested in contributing. Is this something you would accept outside contributions for?

**Comment by andrii-bodnar** [comment]
Hi @awmottaz, thanks a lot for your suggestion, it's a great idea! 🎉 

I would suggest splitting these features into two parts.

> I understand that these features require some level of parsing of source files

If there is a way not to parse files, but use some common approach for all the formats - we would prefer this way. Because file parsing is a difficult thing, there are a lot of file types and it requires a huge effort to correctly support all of them.

The feature with the autocomplete looks not so epic :)

I can see two ways to implement this:
- default autocomplete for source code - somehow attach strings list here.
- custom hotkey shortcut for calling the strings list displaying and then selecting the key to autocomplete.

Also, we should consider the performance - there can be thousands or even millions of strings in a crowdin project.

We are highly [welcome contributions](https://github.com/crowdin/vscode-crowdin/blob/master/CONTRIBUTING.md) and happy to accept them 🙂

**Comment by andrii-bodnar** [comment]
Hi @awmottaz!

We have released a [new version](https://github.com/crowdin/vscode-crowdin/releases/tag/1.4.0) of the plugin with the string keys autocompletion 🎉 

We would be pleased to receive your feedback!
